# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Course'),
            preserve_default=False,
        ),
    ]
