# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_section_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
